### ISSUE TITLE
A few issues using this from ChromeOS but most should be fixable

### ISSUE THREAD

**Issue by spoelstraethan** [sebanc/linuxloops#27]
The `: >/dev/tcp/github.com/80` check won't work on systems where Bash's TCP stack is disabled due to hardening (which is more and more systems but especially ChromeOS).

The `grep` command on ChromeOS doesn't have PCRE enabled, so the `-P` option causes failures which end up failing certain checks that really haven't mattered so far as I've been able to comment those lines.

The biggest hurdle right now is that the `linuxloopsdir` gets defined as a .cache/linuxloops under the SUDO_USER home dir, but the ONLY location where arbitrary binaries can be executed on ChromeOS for quite a while is /usr/local, but there isn't an argument to change the linuxloopsdir and/or the cache directory to /usr/local/cache.

Same story with the `tmp` directory references. The bootstrapdir and the bootstrap_init are all building on top of the linuxloopsdir that is in the SUDO_USER home directory but funny enough it seems like in a few cases the bootstrapdir variable isn't getting populated, so it tries to do it in the regular /tmp/linuxloops directory which is also mounted `+noexec`.

I was hoping I could just export TMPDIR=/usr/local/tmp or set the linuxloopsdir by presetting an environment variable (or passing it in) but that doesn't appear to be supported yet.

Supporting $TMPDIR appears to be a common pattern.

https://superuser.com/a/332616

**Comment by spoelstraethan** [comment]
I'd also HIGHLY recommend running Shellcheck against the script, because it throws a LOT of warnings about quoting issues that could lead to unexpected behaviors.

**Comment by sebanc** [comment]
> The `: >/dev/tcp/github.com/80` check won't work on systems where Bash's TCP stack is disabled due to hardening (which is more and more systems but especially ChromeOS).

It should be very easy to replace with a curl command.

> The `grep` command on ChromeOS doesn't have PCRE enabled, so the `-P` option causes failures which end up failing certain checks that really haven't mattered so far as I've been able to comment those lines.

Those 2 lines are relatively complex checks on the hostname format, it should be possible to find another method if there really is a need.

> The biggest hurdle right now is that the `linuxloopsdir` gets defined as a .cache/linuxloops under the SUDO_USER home dir, but the ONLY location where arbitrary binaries can be executed on ChromeOS for quite a while is /usr/local, but there isn't an argument to change the linuxloopsdir and/or the cache directory to /usr/local/cache.
> Same story with the `tmp` directory references. The bootstrapdir and the bootstrap_init are all building on top of the linuxloopsdir that is in the SUDO_USER home directory but funny enough it seems like in a few cases the bootstrapdir variable isn't getting populated, so it tries to do it in the regular /tmp/linuxloops directory which is also mounted `+noexec`.
> I was hoping I could just export TMPDIR=/usr/local/tmp or set the linuxloopsdir by presetting an environment variable (or passing it in) but that doesn't appear to be supported yet.

As this script run as root, you can specify "-o exec" option for when mounting  `linuxloopsdir`  and `bootstrapdir`.

> I'd also HIGHLY recommend running Shellcheck against the script, because it throws a LOT of warnings about quoting issues that could lead to unexpected behaviors.

I am fine with the output of shell check currently.


Out of curiosity, why would you like to use linuxloops from ChromeOS ?

**Comment by dragon788** [comment]
Since Chrx tends to cause a lot of disruption when setting up a dual boot I've been exploring alternatives for installing a Linux distro from a running ChromeOS. Crap (the Chrultabook partitioning tool) works great and doesn't trigger a ChromeOS repair, but it only handles partitioning, the user still needs to make and boot a USB or use another method to install Linux alongside ChromeOS. I'm hoping to find a method where a USB drive isn't necessary.

**Comment by sebanc** [comment]
So if I understand correctly, the idea would be to create disk images somewhere on the data partition and boot them using RW_LEGACY firmware ? Is that correct ?

I will try to see if the principle would work.

**Comment by dragon788** [comment]
I think the primary use case would be on newer systems where AltFW aka Tianocore is available since Chrx is currently only partially successful in setting up dual boot there. With AltFW as long as partition 12 has been emptied/reformatted to get rid of the janky syslinux/grub config put there by ChromeOS it can typically find valid EFI payloads that have been put in the EFI partition. After running Crap and reformatting p12 I've been able to install Fedora and other distros into the space reclaimed from STATE without touching ROOT-C aka p6/p7 and haven't had any issues with ChromeOS when hopping back and forth.

**Comment by sebanc** [comment]
I have fixed the network check and temporarily disabled the hostname test with `grep -P` under ChromeOS. The script now runs on Brunch, however Brunch does not have all the ChromeOS security features enabled and I do not have a chromebook available to test it.

Could you please test the script by running the following commands and confirm if the script works or if it fails and in that case provide the error message ?
```
curl -L https://raw.githubusercontent.com/sebanc/linuxloops/main/linuxloops -O --create-dirs --output-dir ~/bin
sudo mount -o remount,exec,symfollow /home/chronos/user
bash ${HOME}/bin/linuxloops -distro Arch -ver Stable -env Cinnamon -dst /mnt/stateful_partition/unencrypted/test.img -s 20
```

(Do not test with Ubuntu as the install script will fail, there seems to be an issue with ChromeOS security features and snap)

**Comment by dragon788** [comment]
Just tested this on a freshly switched to Dev mode Chromebook and it doesn't want to allow remounting the home dir (or /tmp).

Despite acting like I could remount /tmp with exec it still failed to execute the bootstrap and exit scripts.

From my extensive experimentation and research the few years I think /usr/local is the only directory not locked down and they didn't plan to lock it down as it is only available in Dev mode. Essentially it needs to be a prefix for everything when running scripts on ChromeOS including replacing /tmp with /usr/local/tmp (but making sure to pre-create it and any other sub-directories because only /usr/local exists owned by root and nothing under it).

**Comment by sebanc** [comment]
Ok, I just pushed a commit to use /usr/local as base for the install process.

Could you try:
```
curl -L https://raw.githubusercontent.com/sebanc/linuxloops/main/linuxloops -O --create-dirs --output-dir /usr/local/bin
bash /usr/local/bin/linuxloops -distro Arch -ver Stable -env Cinnamon -dst /mnt/stateful_partition/unencrypted/test.img -s 20
```

And if there is an issue post the exact log ?

**Comment by dragon788** [comment]
I'll get the exact log later, but it seems to be failing the cheoot bootstrap and exit chroot because it can't execute files from the /tmp location that should be inside the chroot.

I tried working around it by updating the linuxloopsdir and the homedir and bootstrapdir but didn't have much luck.

**Comment by sebanc** [comment]
I think I solved the issue but I don't have a Chromebook to test it.

login as "chronos" from tty2 and run:
```
cd /
sudo curl -L https://raw.githubusercontent.com/sebanc/linuxloops/main/linuxloops -O --create-dirs --output-dir /usr/local/bin
bash linuxloops -distro Arch -ver Stable -env Cinnamon -dst /mnt/stateful_partition/unencrypted/test.img -s 20
```

**Comment by dragon788** [comment]
I'll see about giving this a try this week.

I can also get you access to a Chromebox through a hardware remote access tool that allows VTY2 if you want to use it for development and testing.
